export const GET_ELASTIC_SEARCH_REQUEST = 'GET_ELASTIC_SEARCH_REQUEST'
export const GET_ELASTIC_SEARCH_SUCCESS = 'GET_ELASTIC_SEARCH_SUCCESS'
export const GET_ELASTIC_SEARCH_FAILED = 'GET_ELASTIC_SEARCH_FAILED'
export const GET_ELASTIC_SEARCH_CLEAR = 'GET_ELASTIC_SEARCH_CLEAR'

export const GET_ELASTIC_DETAIL_DATA_REQUEST = 'GET_ELASTIC_DETAIL_DATA_REQUEST'
export const GET_ELASTIC_DETAIL_DATA_SUCCESS = 'GET_ELASTIC_DETAIL_DATA_SUCCESS'
export const GET_ELASTIC_DETAIL_DATA_FAILED = 'GET_ELASTIC_DETAIL_DATA_FAILED'
export const GET_ELASTIC_DETAIL_DATA_CLEAR = 'GET_ELASTIC_DETAIL_DATA_CLEAR'

export const GET_ALL_ITEM_TYPE_DATA_REQUEST = 'GET_ALL_ITEM_TYPE_DATA_REQUEST'
export const GET_ALL_ITEM_TYPE_DATA_SUCCESS = 'GET_ALL_ITEM_TYPE_DATA_SUCCESS'
export const GET_ALL_ITEM_TYPE_DATA_FAILED = 'GET_ALL_ITEM_TYPE_DATA_FAILED'
export const GET_ALL_ITEM_TYPE_DATA_CLEAR = 'GET_ALL_ITEM_TYPE_DATA_CLEAR'

export const GET_ALL_UNIQUE_SUPPLIERS_DATA_REQUEST = 'GET_ALL_UNIQUE_SUPPLIERS_DATA_REQUEST'
export const GET_ALL_UNIQUE_SUPPLIERS_DATA_SUCCESS = 'GET_ALL_UNIQUE_SUPPLIERS_DATA_SUCCESS'
export const GET_ALL_UNIQUE_SUPPLIERS_DATA_FAILED = 'GET_ALL_UNIQUE_SUPPLIERS_DATA_FAILED'
export const GET_ALL_UNIQUE_SUPPLIERS_DATA_CLEAR = 'GET_ALL_UNIQUE_SUPPLIERS_DATA_CLEAR'

export const GET_ALL_UNIQUE_TENDERS_DATA_REQUEST = 'GET_ALL_UNIQUE_TENDERS_DATA_REQUEST'
export const GET_ALL_UNIQUE_TENDERS_DATA_SUCCESS = 'GET_ALL_UNIQUE_TENDERS_DATA_SUCCESS'
export const GET_ALL_UNIQUE_TENDERS_DATA_FAILED = 'GET_ALL_UNIQUE_TENDERS_DATA_FAILED'
export const GET_ALL_UNIQUE_TENDERS_DATA_CLEAR = 'GET_ALL_UNIQUE_TENDERS_DATA_CLEAR'

export const GET_ALL_UNIQUE_ARTICLES_DATA_REQUEST = 'GET_ALL_UNIQUE_ARTICLES_DATA_REQUEST'
export const GET_ALL_UNIQUE_ARTICLES_DATA_SUCCESS = 'GET_ALL_UNIQUE_ARTICLES_DATA_SUCCESS'
export const GET_ALL_UNIQUE_ARTICLES_DATA_FAILED = 'GET_ALL_UNIQUE_ARTICLES_DATA_FAILED'
export const GET_ALL_UNIQUE_ARTICLES_DATA_CLEAR = 'GET_ALL_UNIQUE_ARTICLES_DATA_CLEAR'

export const GET_ALL_PROVIDERS_AND_TRADEMARKS_DATA_REQUEST = 'GET_ALL_PROVIDERS_AND_TRADEMARKS_DATA_REQUEST'
export const GET_ALL_PROVIDERS_AND_TRADEMARKS_DATA_SUCCESS = 'GET_ALL_PROVIDERS_AND_TRADEMARKS_DATA_SUCCESS'
export const GET_ALL_PROVIDERS_AND_TRADEMARKS_DATA_FAILED = 'GET_ALL_PROVIDERS_AND_TRADEMARKS_DATA_FAILED'
export const GET_ALL_PROVIDERS_AND_TRADEMARKS_DATA_CLEAR = 'GET_ALL_PROVIDERS_AND_TRADEMARKS_DATA_CLEAR'

export const SET_ELASTIC_SEARCH_PARAMS = 'SET_ELASTIC_SEARCH_PARAMS'
export const SET_FILTER_PARAMS = 'SET_FILTER_PARAMS'

/*
export const GET_LIST_OF_FILES_REQUEST = 'GET_LIST_OF_FILES_REQUEST'
export const GET_LIST_OF_FILES_SUCCESS = 'GET_LIST_OF_FILES_SUCCESS'
export const GET_LIST_OF_FILES_FAILED = 'GET_LIST_OF_FILES_FAILED'
export const GET_LIST_OF_FILES_CLEAR = 'GET_LIST_OF_FILES_CLEAR'

export const GET_FILE_CONTENT_BY_NAME_REQUEST = 'GET_FILE_CONTENT_BY_NAME_REQUEST'
export const GET_FILE_CONTENT_BY_NAME_SUCCESS = 'GET_FILE_CONTENT_BY_NAME_SUCCESS'
export const GET_FILE_CONTENT_BY_NAME_FAILED = 'GET_FILE_CONTENT_BY_NAME_FAILED'
export const GET_FILE_CONTENT_BY_NAME_CLEAR = 'GET_FILE_CONTENT_BY_NAME_CLEAR'

export const SAVE_FILE_CONTENT_BY_NAME_REQUEST = 'SAVE_FILE_CONTENT_BY_NAME_REQUEST'
export const SAVE_FILE_CONTENT_BY_NAME_SUCCESS = 'SAVE_FILE_CONTENT_BY_NAME_SUCCESS'
export const SAVE_FILE_CONTENT_BY_NAME_FAILED = 'SAVE_FILE_CONTENT_BY_NAME_FAILED'
export const SAVE_FILE_CONTENT_BY_NAME_CLEAR = 'SAVE_FILE_CONTENT_BY_NAME_CLEAR'
*/